name: CI/CD Pipeline for Task Management App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pr-checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          unset NODE_EXTRA_CA_CERTS
          cd frontend && npm ci
          cd ../backend && npm ci

      - name: Run linters
        run: |
          unset NODE_EXTRA_CA_CERTS
          cd frontend && npm run lint
          cd ../backend && npm run lint

      - name: Run unit tests
        run: |
          unset NODE_EXTRA_CA_CERTS
          cd frontend && npm test -- --passWithNoTests
          cd ../backend && npm test
